### ISSUE TITLE
Error in demo/simple_visualization.py : [w] Data not available on remote server

### ISSUE THREAD

**Issue by Pallavi-code** [krematas/soccerontable#16]
Hi, 
      I am using your code to test the AR/VR. Thanks for your contribution. I need one help in executing the code. I am stuck at last stage "demo/simple_visualization.py" script. I have successfully completed all the steps and data is  been created. But when I run demo/simple_visualization.py I am getting the below error.

[i] Requesting "texture.png" from remote server
I0122 12:15:35.454744 13646 __init__.py:49] [i] Requesting "texture.png" from remote server
[w] Data not available on remote server
W0122 12:15:36.370683 13646 __init__.py:53] [w] Data not available on remote server
Traceback (most recent call last):
  File "demo/simple_visualization.py", line 157, in <module>
    field['u_texture'] = data.get(join(opt.path_to_data, 'texture.png'))
  File "/usr/local/lib/python3.6/dist-packages/glumpy/data/__init__.py", line 167, in get
    return load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/glumpy/data/__init__.py", line 173, in load
    extension = os.path.basename(filename).split('.')[-1]
  File "/usr/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Please guide me to resolve this issue.

**Comment by krematas** [comment]
I think it doesn't find the texture.png. I will check if its in the repo, but a quick solution would be to have a simple image as "texture.png" (that used to be the soccer field).
